export const colors = {
  primary: "#1B4332",
  primaryLight: "#2D6A4F",
  primaryLighter: "#40916C",
  accent: "#F77F00",
  accentLight: "#FCBF49",
  background: "#FAFAF9",
  surface: "#FFFFFF",
  border: "#E7E5E4",
  borderLight: "#F5F5F4",
  textPrimary: "#1C1917",
  textSecondary: "#57534E",
  textTertiary: "#A8A29E",
  textInverse: "#FFFFFF",
  success: "#22C55E",
  warning: "#F59E0B",
  error: "#EF4444",
  info: "#3B82F6",
  whatsapp: "#25D366",
  email: "#4285F4",
  pipeline: {
    newLead: "#93C5FD",
    contacted: "#C4B5FD",
    conversation: "#FDE68A",
    negotiation: "#FDBA74",
    sampleSent: "#86EFAC",
    closedWon: "#22C55E",
    closedLost: "#FCA5A5",
  },
} as const;

export const typography = {
  h1: { size: "28px", weight: "700", family: "var(--font-heading)" },
  h2: { size: "22px", weight: "600", family: "var(--font-heading)" },
  h3: { size: "18px", weight: "600", family: "var(--font-heading)" },
  h4: { size: "16px", weight: "600", family: "var(--font-body)" },
  body: { size: "14px", weight: "400", family: "var(--font-body)" },
  bodySmall: { size: "13px", weight: "400", family: "var(--font-body)" },
  caption: { size: "12px", weight: "400", family: "var(--font-body)" },
  overline: { size: "11px", weight: "600", family: "var(--font-body)" },
} as const;
