"""add_leads_and_preferences

Revision ID: 0139aeb56ce6
Revises: b653ae7907d2
Create Date: 2026-04-02 13:16:21.287515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0139aeb56ce6'
down_revision: Union[str, None] = 'b653ae7907d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_preferences',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ignore_below_qty_mt', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ignore_countries', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_non_lead_if_no_catalog_match', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('reply_tone', sa.String(length=20), server_default='formal', nullable=False),
    sa.Column('reply_language', sa.String(length=20), server_default='match_sender', nullable=False),
    sa.Column('include_fob_price', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('include_cfr_quote', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('include_certifications', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('include_moq', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('high_value_threshold_mt', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('high_value_reply_style', sa.Text(), nullable=True),
    sa.Column('custom_reply_instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('inbound_leads',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email_account_id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=100), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('non_lead_reason', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_phone', sa.String(length=50), nullable=True),
    sa.Column('sender_company', sa.String(length=255), nullable=True),
    sa.Column('sender_designation', sa.String(length=255), nullable=True),
    sa.Column('matched_contact_id', sa.UUID(), nullable=True),
    sa.Column('matched_contact_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('matched_company_id', sa.UUID(), nullable=True),
    sa.Column('matched_company_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('body_full', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thread_message_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('products_mentioned', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('quantities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('target_price', sa.String(length=100), nullable=True),
    sa.Column('delivery_terms', sa.String(length=20), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('specific_questions', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('is_high_value', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('draft_reply', sa.Text(), nullable=True),
    sa.Column('draft_reply_explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inbound_leads_status', 'inbound_leads', ['tenant_id', 'classification', 'status'], unique=False)
    op.create_index('ix_inbound_leads_tenant_id', 'inbound_leads', ['tenant_id'], unique=False)
    op.create_index('ix_inbound_leads_thread', 'inbound_leads', ['tenant_id', 'gmail_thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inbound_leads_thread', table_name='inbound_leads')
    op.drop_index('ix_inbound_leads_tenant_id', table_name='inbound_leads')
    op.drop_index('ix_inbound_leads_status', table_name='inbound_leads')
    op.drop_table('inbound_leads')
    op.drop_table('lead_preferences')
    # ### end Alembic commands ###
