"""enrich_entities_company_contact_opportunity

Revision ID: 0f85e49321ff
Revises: d3ff539d1e1a
Create Date: 2026-04-13 23:56:16.696227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f85e49321ff'
down_revision: Union[str, None] = 'd3ff539d1e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('year_established', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('number_of_employees', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('annual_revenue_usd', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('companies', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('bank_country', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('bank_swift_code', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('social_media', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('known_suppliers', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('trade_references', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('companies', 'total_inquiries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('companies', 'total_deals_won',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('contacts', sa.Column('salutation', sa.String(length=10), nullable=True))
    op.add_column('contacts', sa.Column('secondary_email', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('secondary_phone', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('do_not_contact', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('contacts', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('contacts', 'is_decision_maker',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('contacts', 'total_interactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('pipeline_opportunities', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('competitor_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('container_type', sa.String(length=20), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('number_of_containers', sa.Integer(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('target_shipment_date', sa.Date(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('shipping_line', sa.String(length=255), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('packaging_requirements', sa.Text(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('quality_specifications', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('follow_up_date', sa.Date(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('sample_approved', sa.Boolean(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('sample_feedback', sa.Text(), nullable=True))
    op.alter_column('pipeline_opportunities', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('pipeline_opportunities', 'probability',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_opportunities', 'sample_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_opportunities', 'sample_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pipeline_opportunities', 'probability',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_opportunities', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.drop_column('pipeline_opportunities', 'sample_feedback')
    op.drop_column('pipeline_opportunities', 'sample_approved')
    op.drop_column('pipeline_opportunities', 'follow_up_date')
    op.drop_column('pipeline_opportunities', 'quality_specifications')
    op.drop_column('pipeline_opportunities', 'packaging_requirements')
    op.drop_column('pipeline_opportunities', 'shipping_line')
    op.drop_column('pipeline_opportunities', 'target_shipment_date')
    op.drop_column('pipeline_opportunities', 'number_of_containers')
    op.drop_column('pipeline_opportunities', 'container_type')
    op.drop_column('pipeline_opportunities', 'competitor_price')
    op.drop_column('pipeline_opportunities', 'title')
    op.alter_column('contacts', 'total_interactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('contacts', 'is_decision_maker',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('contacts', 'last_contacted_at')
    op.drop_column('contacts', 'avatar_url')
    op.drop_column('contacts', 'do_not_contact')
    op.drop_column('contacts', 'city')
    op.drop_column('contacts', 'country')
    op.drop_column('contacts', 'secondary_phone')
    op.drop_column('contacts', 'secondary_email')
    op.drop_column('contacts', 'salutation')
    op.alter_column('companies', 'total_deals_won',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('companies', 'total_inquiries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('companies', 'trade_references')
    op.drop_column('companies', 'known_suppliers')
    op.drop_column('companies', 'social_media')
    op.drop_column('companies', 'bank_swift_code')
    op.drop_column('companies', 'bank_country')
    op.drop_column('companies', 'bank_name')
    op.drop_column('companies', 'registration_number')
    op.drop_column('companies', 'annual_revenue_usd')
    op.drop_column('companies', 'number_of_employees')
    op.drop_column('companies', 'year_established')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'postal_code')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'description')
    # ### end Alembic commands ###
