"""add_product_trade_fields

Revision ID: 44a58bc655f3
Revises: cf8aad188dbc
Create Date: 2026-04-01 12:17:08.713261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44a58bc655f3'
down_revision: Union[str, None] = 'cf8aad188dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_grades', sa.Column('packaging_type', sa.String(length=100), nullable=True))
    op.add_column('product_grades', sa.Column('packaging_weight_kg', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('product_grades', sa.Column('moq_mt', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('products', sa.Column('default_loading_port_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('shelf_life_days', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('certifications', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('aliases', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('capacity_20ft_mt', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('products', sa.Column('capacity_40ft_mt', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('products', sa.Column('capacity_40ft_hc_mt', sa.Numeric(precision=6, scale=2), nullable=True))
    op.create_foreign_key(None, 'products', 'ports', ['default_loading_port_id'], ['id'])
    op.add_column('tenant_defaults', sa.Column('supported_incoterms', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_defaults', 'supported_incoterms')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'capacity_40ft_hc_mt')
    op.drop_column('products', 'capacity_40ft_mt')
    op.drop_column('products', 'capacity_20ft_mt')
    op.drop_column('products', 'aliases')
    op.drop_column('products', 'certifications')
    op.drop_column('products', 'shelf_life_days')
    op.drop_column('products', 'default_loading_port_id')
    op.drop_column('product_grades', 'moq_mt')
    op.drop_column('product_grades', 'packaging_weight_kg')
    op.drop_column('product_grades', 'packaging_type')
    # ### end Alembic commands ###
