"""add_commodity_references

Revision ID: ca08c96316c1
Revises: 44a58bc655f3
Create Date: 2026-04-01 12:47:43.448579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca08c96316c1'
down_revision: Union[str, None] = '44a58bc655f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity_references',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hs_codes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('aliases', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('default_capacity_20ft_mt', sa.String(length=10), nullable=True),
    sa.Column('default_capacity_40ft_mt', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_commodity_ref_name', 'commodity_references', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commodity_ref_name', table_name='commodity_references')
    op.drop_table('commodity_references')
    # ### end Alembic commands ###
