"""add_catalog_pricing_ports

Revision ID: cf8aad188dbc
Revises: acd153b91ee4
Create Date: 2026-04-01 12:08:39.757013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf8aad188dbc'
down_revision: Union[str, None] = 'acd153b91ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ports',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ports_country', 'ports', ['country'], unique=False)
    op.create_table('freight_rates',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('origin_port_id', sa.UUID(), nullable=False),
    sa.Column('destination_port_id', sa.UUID(), nullable=False),
    sa.Column('container_type', sa.String(length=20), server_default='20ft', nullable=False),
    sa.Column('rate_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transit_days', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_freight_rates_ports', 'freight_rates', ['origin_port_id', 'destination_port_id'], unique=False)
    op.create_index('ix_freight_rates_tenant_id', 'freight_rates', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('origin_country', sa.String(length=100), nullable=False),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'origin_country', name='uq_product_tenant_name_origin')
    )
    op.create_index('ix_products_tenant_id', 'products', ['tenant_id'], unique=False)
    op.create_table('tenant_defaults',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('default_origin_port_id', sa.UUID(), nullable=True),
    sa.Column('default_currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('default_container_type', sa.String(length=20), server_default='20ft', nullable=False),
    sa.Column('default_payment_terms', sa.String(length=255), nullable=True),
    sa.Column('custom_settings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_origin_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('product_varieties',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_varieties_product_id', 'product_varieties', ['product_id'], unique=False)
    op.create_table('product_grades',
    sa.Column('variety_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specifications', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variety_id'], ['product_varieties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_grades_variety_id', 'product_grades', ['variety_id'], unique=False)
    op.create_table('fob_prices',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('origin_port_id', sa.UUID(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price_usd_per_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_usd_per_mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['product_grades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fob_prices_grade_id', 'fob_prices', ['grade_id'], unique=False)
    op.create_index('ix_fob_prices_tenant_date', 'fob_prices', ['tenant_id', 'price_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fob_prices_tenant_date', table_name='fob_prices')
    op.drop_index('ix_fob_prices_grade_id', table_name='fob_prices')
    op.drop_table('fob_prices')
    op.drop_index('ix_product_grades_variety_id', table_name='product_grades')
    op.drop_table('product_grades')
    op.drop_index('ix_product_varieties_product_id', table_name='product_varieties')
    op.drop_table('product_varieties')
    op.drop_table('tenant_defaults')
    op.drop_index('ix_products_tenant_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_freight_rates_tenant_id', table_name='freight_rates')
    op.drop_index('ix_freight_rates_ports', table_name='freight_rates')
    op.drop_table('freight_rates')
    op.drop_index('ix_ports_country', table_name='ports')
    op.drop_table('ports')
    # ### end Alembic commands ###
