"""expand_entities_company_contact_opportunity

Revision ID: d3ff539d1e1a
Revises: 0139aeb56ce6
Create Date: 2026-04-02 18:29:55.126347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3ff539d1e1a'
down_revision: Union[str, None] = '0139aeb56ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('company_type', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('company_size', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('preferred_origins', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('preferred_incoterms', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('preferred_payment_terms', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('certifications_required', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('destination_ports', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('tax_id', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('rating', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('first_contact_date', sa.Date(), nullable=True))
    op.add_column('companies', sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('total_inquiries', sa.Integer(), server_default='0', nullable=False))
    op.add_column('companies', sa.Column('total_deals_won', sa.Integer(), server_default='0', nullable=False))
    op.add_column('companies', sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('contacts', sa.Column('whatsapp_number', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('is_decision_maker', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('contacts', sa.Column('preferred_language', sa.String(length=10), nullable=True))
    op.add_column('contacts', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('preferred_channel', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contacts', sa.Column('total_interactions', sa.Integer(), server_default='0', nullable=False))
    op.add_column('pipeline_opportunities', sa.Column('lead_id', sa.UUID(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('product_id', sa.UUID(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('grade_id', sa.UUID(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('quantity_mt', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('our_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('estimated_value_usd', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False))
    op.add_column('pipeline_opportunities', sa.Column('incoterms', sa.String(length=20), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('payment_terms', sa.String(length=100), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('origin_port_id', sa.UUID(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('destination_port_id', sa.UUID(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('expected_close_date', sa.Date(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('probability', sa.Integer(), server_default='0', nullable=False))
    op.add_column('pipeline_opportunities', sa.Column('sample_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('pipeline_opportunities', sa.Column('sample_sent_date', sa.Date(), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('loss_reason', sa.String(length=255), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('documents', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('pipeline_opportunities', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'pipeline_opportunities', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pipeline_opportunities', 'ports', ['origin_port_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pipeline_opportunities', 'ports', ['destination_port_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_opportunities', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_opportunities', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_opportunities', type_='foreignkey')
    op.drop_column('pipeline_opportunities', 'last_activity_at')
    op.drop_column('pipeline_opportunities', 'documents')
    op.drop_column('pipeline_opportunities', 'tags')
    op.drop_column('pipeline_opportunities', 'loss_reason')
    op.drop_column('pipeline_opportunities', 'sample_sent_date')
    op.drop_column('pipeline_opportunities', 'sample_sent')
    op.drop_column('pipeline_opportunities', 'probability')
    op.drop_column('pipeline_opportunities', 'expected_close_date')
    op.drop_column('pipeline_opportunities', 'destination_port_id')
    op.drop_column('pipeline_opportunities', 'origin_port_id')
    op.drop_column('pipeline_opportunities', 'payment_terms')
    op.drop_column('pipeline_opportunities', 'incoterms')
    op.drop_column('pipeline_opportunities', 'currency')
    op.drop_column('pipeline_opportunities', 'estimated_value_usd')
    op.drop_column('pipeline_opportunities', 'our_price')
    op.drop_column('pipeline_opportunities', 'target_price')
    op.drop_column('pipeline_opportunities', 'quantity_mt')
    op.drop_column('pipeline_opportunities', 'grade_id')
    op.drop_column('pipeline_opportunities', 'product_id')
    op.drop_column('pipeline_opportunities', 'lead_id')
    op.drop_column('contacts', 'total_interactions')
    op.drop_column('contacts', 'first_seen_at')
    op.drop_column('contacts', 'linkedin_url')
    op.drop_column('contacts', 'preferred_channel')
    op.drop_column('contacts', 'timezone')
    op.drop_column('contacts', 'preferred_language')
    op.drop_column('contacts', 'is_decision_maker')
    op.drop_column('contacts', 'department')
    op.drop_column('contacts', 'whatsapp_number')
    op.drop_column('companies', 'total_revenue')
    op.drop_column('companies', 'total_deals_won')
    op.drop_column('companies', 'total_inquiries')
    op.drop_column('companies', 'last_interaction_at')
    op.drop_column('companies', 'first_contact_date')
    op.drop_column('companies', 'tags')
    op.drop_column('companies', 'rating')
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'linkedin_url')
    op.drop_column('companies', 'tax_id')
    op.drop_column('companies', 'destination_ports')
    op.drop_column('companies', 'certifications_required')
    op.drop_column('companies', 'preferred_payment_terms')
    op.drop_column('companies', 'preferred_incoterms')
    op.drop_column('companies', 'preferred_origins')
    op.drop_column('companies', 'company_size')
    op.drop_column('companies', 'company_type')
    op.drop_column('companies', 'city')
    # ### end Alembic commands ###
