"""initial_schema

Revision ID: e521f016f212
Revises: 
Create Date: 2026-03-31 16:28:29.457753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e521f016f212'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('free_trial', 'starter', 'growth', 'pro', name='plan_type'), server_default='free_trial', nullable=False),
    sa.Column('commodities', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('target_markets', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('certifications', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('gupshup_app_id', sa.String(length=255), nullable=True),
    sa.Column('gupshup_api_key', sa.Text(), nullable=True),
    sa.Column('sendgrid_api_key', sa.Text(), nullable=True),
    sa.Column('email_warmup_state', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('supabase_org_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_log',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'agent', 'system', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_tenant_id'), 'activity_log', ['tenant_id'], unique=False)
    op.create_table('companies',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('commodities', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('import_volume_annual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shipment_frequency', sa.String(length=100), nullable=True),
    sa.Column('last_shipment_date', sa.Date(), nullable=True),
    sa.Column('enrichment_status', sa.Enum('not_enriched', 'enriching', 'partially_enriched', 'enriched', name='enrichment_status'), server_default='not_enriched', nullable=False),
    sa.Column('enrichment_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('source', sa.Enum('discovery', 'manual', 'import_', name='company_source'), server_default='manual', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.create_table('contact_lists',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_lists_tenant_id'), 'contact_lists', ['tenant_id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_tenant_id'), 'pipeline_stages', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supabase_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='user_role'), server_default='member', nullable=False),
    sa.Column('gmail_oauth_token', sa.Text(), nullable=True),
    sa.Column('outlook_oauth_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supabase_user_id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('buyer_discovery', 'company_research', 'contact_enrichment', 'message_compose', 'reply_suggest', 'campaign_analytics', name='agent_task_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='agent_task_status'), server_default='pending', nullable=False),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('current_step_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('output_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('credits_consumed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_tenant_id'), 'agent_tasks', ['tenant_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('email', 'whatsapp', 'multi_channel', name='campaign_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', 'cancelled', name='campaign_status'), server_default='draft', nullable=False),
    sa.Column('contact_list_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_list_id'], ['contact_lists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('opted_in_whatsapp', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('opted_in_email', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enrichment_status', sa.Enum('not_enriched', 'enriching', 'enriched', name='contact_enrichment_status'), server_default='not_enriched', nullable=False),
    sa.Column('source', sa.Enum('manual', 'import_', 'discovery', 'enrichment', name='contact_source'), server_default='manual', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_tenant_email', 'contacts', ['tenant_id', 'email'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_index('ix_contacts_tenant_phone', 'contacts', ['tenant_id', 'phone'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('genie_query', 'enrichment', 'ai_compose', 'ai_reply', name='credit_action_type'), nullable=False),
    sa.Column('credits_consumed', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_tenant_id'), 'credit_transactions', ['tenant_id'], unique=False)
    op.create_table('campaign_steps',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', name='channel_type'), nullable=False),
    sa.Column('delay_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('condition', sa.Enum('no_reply', 'no_open', 'always', name='step_condition'), server_default='always', nullable=False),
    sa.Column('template_content', sa.Text(), nullable=True),
    sa.Column('whatsapp_template_name', sa.String(length=255), nullable=True),
    sa.Column('subject_template', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_steps_campaign_id'), 'campaign_steps', ['campaign_id'], unique=False)
    op.create_table('contact_list_members',
    sa.Column('contact_list_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_list_id'], ['contact_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_list_members_contact_id'), 'contact_list_members', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_list_members_contact_list_id'), 'contact_list_members', ['contact_list_id'], unique=False)
    op.create_table('pipeline_opportunities',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('discovery', 'campaign', 'manual', name='opportunity_source'), server_default='manual', nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('commodity', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_opportunities_stage_id'), 'pipeline_opportunities', ['stage_id'], unique=False)
    op.create_index(op.f('ix_pipeline_opportunities_tenant_id'), 'pipeline_opportunities', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('campaign_step_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('sent_by', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('email', 'whatsapp', name='channel_type'), nullable=False),
    sa.Column('direction', sa.Enum('outbound', 'inbound', name='message_direction'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sending', 'sent', 'delivered', 'opened', 'clicked', 'replied', 'failed', 'bounced', name='message_status'), server_default='queued', nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('personalization_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_step_id'], ['campaign_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_tenant_channel_direction', 'messages', ['tenant_id', 'channel', 'direction'], unique=False)
    op.create_index('ix_messages_tenant_contact', 'messages', ['tenant_id', 'contact_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_index('ix_messages_tenant_status', 'messages', ['tenant_id', 'status'], unique=False)
    op.create_table('sequences',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('current_step_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'replied', 'unsubscribed', 'paused', name='sequence_status'), server_default='active', nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_step_id'], ['campaign_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequences_campaign_id'), 'sequences', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_sequences_contact_id'), 'sequences', ['contact_id'], unique=False)
    op.create_index(op.f('ix_sequences_tenant_id'), 'sequences', ['tenant_id'], unique=False)
    op.create_table('message_events',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('sent', 'delivered', 'opened', 'clicked', 'bounced', 'failed', 'read', 'replied', name='message_event_type'), nullable=False),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_events_message_id'), 'message_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_events_tenant_id'), 'message_events', ['tenant_id'], unique=False)
    op.create_table('reply_suggestions',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.Enum('interested', 'price_inquiry', 'sample_request', 'meeting_request', 'not_interested', 'auto_reply', 'out_of_office', name='reply_classification'), nullable=False),
    sa.Column('suggested_reply_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'edited', 'rejected', 'sent', name='suggestion_status'), server_default='pending', nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_suggestions_message_id'), 'reply_suggestions', ['message_id'], unique=False)
    op.create_index(op.f('ix_reply_suggestions_tenant_id'), 'reply_suggestions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reply_suggestions_tenant_id'), table_name='reply_suggestions')
    op.drop_index(op.f('ix_reply_suggestions_message_id'), table_name='reply_suggestions')
    op.drop_table('reply_suggestions')
    op.drop_index(op.f('ix_message_events_tenant_id'), table_name='message_events')
    op.drop_index(op.f('ix_message_events_message_id'), table_name='message_events')
    op.drop_table('message_events')
    op.drop_index(op.f('ix_sequences_tenant_id'), table_name='sequences')
    op.drop_index(op.f('ix_sequences_contact_id'), table_name='sequences')
    op.drop_index(op.f('ix_sequences_campaign_id'), table_name='sequences')
    op.drop_table('sequences')
    op.drop_index('ix_messages_tenant_status', table_name='messages')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index('ix_messages_tenant_contact', table_name='messages')
    op.drop_index('ix_messages_tenant_channel_direction', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_pipeline_opportunities_tenant_id'), table_name='pipeline_opportunities')
    op.drop_index(op.f('ix_pipeline_opportunities_stage_id'), table_name='pipeline_opportunities')
    op.drop_table('pipeline_opportunities')
    op.drop_index(op.f('ix_contact_list_members_contact_list_id'), table_name='contact_list_members')
    op.drop_index(op.f('ix_contact_list_members_contact_id'), table_name='contact_list_members')
    op.drop_table('contact_list_members')
    op.drop_index(op.f('ix_campaign_steps_campaign_id'), table_name='campaign_steps')
    op.drop_table('campaign_steps')
    op.drop_index(op.f('ix_credit_transactions_tenant_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index('ix_contacts_tenant_phone', table_name='contacts')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index('ix_contacts_tenant_email', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_agent_tasks_tenant_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pipeline_stages_tenant_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_contact_lists_tenant_id'), table_name='contact_lists')
    op.drop_table('contact_lists')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_activity_log_tenant_id'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_table('tenants')
    # ### end Alembic commands ###
