"""add_shipments_interests

Revision ID: f9a3bd8bdd6e
Revises: 5d865cd221d5
Create Date: 2026-04-15 15:46:57.230587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9a3bd8bdd6e'
down_revision: Union[str, None] = '5d865cd221d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_shipment_summaries',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_through_date', sa.Date(), nullable=True),
    sa.Column('source_providers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('total_shipments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_volume_mt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_value_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('shipments_12mo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('volume_12mo_mt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('value_12mo_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('role', sa.Enum('importer', 'exporter', 're_exporter', 'both', 'unknown', name='trade_role'), nullable=True),
    sa.Column('cadence', sa.Enum('monthly', 'quarterly', 'biannual', 'annual', 'irregular', 'none_', name='shipment_cadence'), nullable=True),
    sa.Column('avg_unit_price_usd_per_mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('top_partners', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('top_lanes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('top_commodities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_series', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('catalog_match_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('catalog_match_volume_mt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'company_id', name='uq_shipment_summary_tenant_company')
    )
    op.create_index(op.f('ix_company_shipment_summaries_company_id'), 'company_shipment_summaries', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_shipment_summaries_tenant_id'), 'company_shipment_summaries', ['tenant_id'], unique=False)
    op.create_table('shipments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.Enum('import', 'export', name='shipment_direction'), nullable=False),
    sa.Column('commodity_text', sa.String(length=255), nullable=False),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('origin_country', sa.String(length=100), nullable=False),
    sa.Column('destination_country', sa.String(length=100), nullable=False),
    sa.Column('origin_port_id', sa.UUID(), nullable=True),
    sa.Column('destination_port_id', sa.UUID(), nullable=True),
    sa.Column('origin_port_text', sa.String(length=255), nullable=True),
    sa.Column('destination_port_text', sa.String(length=255), nullable=True),
    sa.Column('volume_mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_price_usd_per_mt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('value_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('trade_partner_name', sa.String(length=255), nullable=True),
    sa.Column('trade_partner_country', sa.String(length=100), nullable=True),
    sa.Column('trade_partner_company_id', sa.UUID(), nullable=True),
    sa.Column('matched_product_id', sa.UUID(), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_partner_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', name='uq_shipments_source')
    )
    op.create_index('ix_shipments_company_date', 'shipments', ['company_id', 'shipment_date'], unique=False)
    op.create_index('ix_shipments_hs', 'shipments', ['hs_code'], unique=False)
    op.create_index('ix_shipments_tenant_company', 'shipments', ['tenant_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_shipments_tenant_id'), 'shipments', ['tenant_id'], unique=False)
    op.create_table('product_port_interests',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variety_id', sa.UUID(), nullable=True),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('destination_port_id', sa.UUID(), nullable=True),
    sa.Column('origin_port_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('buyer', 'seller', 'both', name='interest_role'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'shipment_data', 'email_thread', 'whatsapp_thread', 'enrichment', 'campaign_reply', 'onboarding_import', name='interest_source'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('confidence_level', sa.Enum('low', 'medium', 'high', name='confidence_level'), nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('suggested', 'confirmed', 'rejected', 'stale', name='interest_status'), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_id'], ['product_grades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variety_id'], ['product_varieties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ppi_company', 'product_port_interests', ['company_id'], unique=False)
    op.create_index('ix_ppi_contact', 'product_port_interests', ['contact_id'], unique=False)
    op.create_index('ix_ppi_product', 'product_port_interests', ['product_id'], unique=False)
    op.create_index('ix_ppi_tenant', 'product_port_interests', ['tenant_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_ppi_tenant', table_name='product_port_interests')
    op.drop_index('ix_ppi_product', table_name='product_port_interests')
    op.drop_index('ix_ppi_contact', table_name='product_port_interests')
    op.drop_index('ix_ppi_company', table_name='product_port_interests')
    op.drop_table('product_port_interests')
    op.drop_index(op.f('ix_shipments_tenant_id'), table_name='shipments')
    op.drop_index('ix_shipments_tenant_company', table_name='shipments')
    op.drop_index('ix_shipments_hs', table_name='shipments')
    op.drop_index('ix_shipments_company_date', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_company_shipment_summaries_tenant_id'), table_name='company_shipment_summaries')
    op.drop_index(op.f('ix_company_shipment_summaries_company_id'), table_name='company_shipment_summaries')
    op.drop_table('company_shipment_summaries')
